apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-app
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - image: quay.io/nlembers/summit-2024-web-app:latest
          name: summit-2024-web-app
          imagePullPolicy: IfNotPresent
          env:
            - name: BACKEND_HOST
              value: "monolith-app"
            - name: BACKEND_PORT
              value: "8080"
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-app
  name: web-app
spec:
  ports:
    - name: http
      port: 3000
  selector:
    app: web-app
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: web-app
  name: web-app
spec:
  port:
    targetPort: http
  to:
    name: web-app
    weight: 100
