apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-app
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - image: quay.io/nlembers/app-mod-web-app:latest
          name: app-mod-web-app
          imagePullPolicy: IfNotPresent
          env:
            - name: BACKEND_HOST
              value: "monolith-app"
            - name: BACKEND_PORT
              value: "8080"
          ports:
            - containerPort: 3000
              protocol: TCP
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 1
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 15
